---
  #######################################
  # SLOWCGI
  #######################################

  - name: slowcgi - started
    service: name=slowcgi state=started

  - name: slowcgi - enable
    shell: rcctl enable slowcgi
