#python-2.7.14p1 for OpenBSD 6.3
#python-2.7.14 for OpenBSD 6.2

# BASE
install_url: https://ftp.fau.de/pub/OpenBSD
dns_name: node3.wurstbot.com
node_number: 3
node_ip: 80.240.28.59
# admin_email: s.schmidbauer@gmail.com
# admin_user: admin
admin_pass: supersecret

# SYSTEM AND PACKAGE UPDATES
update_mode: false

# BIRD
bgp_ha_ip: 45.76.81.117
bgp_pass: supersecret

# PF
ext_if: vio0

# ACME-client
acme_aliases:
  - repo.wurstbot.com
  - repo{{ node_number }}.wurstbot.com
  - wiki.wurstbot.com
  - wiki{{ node_number }}.wurstbot.com
  - owncloud.wurstbot.com
  - owncloud{{ node_number }}.wurstbot.com

# ZABBIX
zabbix_db_pass: supersecret

# SMTPD
smtpd_pass: supersecret
