#python-2.7.14p1 for OpenBSD 6.3
#python-2.7.14 for OpenBSD 6.2

# BASE
install_url: https://ftp.bit.nl/pub/OpenBSD
dns_name: node6.wurstbot.com
node_number: 6
node_ip: 209.250.244.111
# admin_email: s.schmidbauer@gmail.com
# admin_user: admin
admin_pass: supersecret

# SYSTEM AND PACKAGE UPDATES
update_mode: false

# BIRD
bgp_pass: supersecret

# PF
ext_if: vio0

# VPN
iked_tunnels:
  wurstbot_to_managedcloudsoftware:
    vpn_peer_ip: 62.195.130.48
    vpn_local_ip: "{{ node_ip }}"
    vpn_remote_ip: 62.195.130.48
    vpn_psk: supersecret
    vpn_tunnel_bandwidth: 1M

# ACME-client
acme_aliases:
  - mail.wurstbot.com
  - mail{{ node_number }}.wurstbot.com
  - repo.wurstbot.com
  - repo{{ node_number }}.wurstbot.com
  - wiki.wurstbot.com
  - wiki{{ node_number }}.wurstbot.com
  - owncloud.wurstbot.com
  - owncloud{{ node_number }}.wurstbot.com

# ZABBIX
zabbix_db_pass: supersecret

# SMTPD
smtpd_pass: supersecret
