#python-2.7.14p1 for OpenBSD 6.3
#python-2.7.14 for OpenBSD 6.2

# BASE
install_url: https://ftp.fsn.hu/pub/OpenBSD
dns_name: node2.wurstbot.com
node_number: 2
node_ip: 46.36.36.48
# admin_email: s.schmidbauer@gmail.com
# admin_user: admin
admin_pass: supersecret
extra_packages:
  - pftop
  - rsync-3.1.3
  - screen-4.0.3p6
  - unzip-6.0p11

# SYSTEM AND PACKAGE UPDATES
update_mode: false

# PF
ext_if: re0

# ACME-client
acme_aliases:
  - zabbix.wurstbot.com
  - zabbix{{ node_number }}.wurstbot.com
  - nagios.wurstbot.com
  - nagios{{ node_number }}.wurstbot.com

# ZABBIX SERVER
zabbix_db_pass: supersecret

# SQUID
squid_cache_mem: 512

# SMTPD
smtpd_pass: supersecret

# NAGIOS
nagios_server: true
nagios_password: supersecret

# MYSQL replication related
mysql_root_pass: "supersecret"
mysql_repl_pass: "supersecret"
mysql_is_master: true
