#python-2.7.14p1 for OpenBSD 6.3
#python-2.7.14 for OpenBSD 6.2

# BASE
install_url: https://ftp.bit.nl/pub/OpenBSD
dns_name: node5.wurstbot.com
node_number: 5
node_ip: 45.32.185.50
# admin_email: s.schmidbauer@gmail.com
# admin_user: admin
admin_pass: supersecret

# SYSTEM AND PACKAGE UPDATES
update_mode: false

# BIRD
bgp_pass: supersecret

# PF
ext_if: vio0

# ACME-client
acme_aliases:
  - zabbix.wurstbot.com
  - zabbix{{ node_number }}.wurstbot.com
  - nagios.wurstbot.com
  - nagios{{ node_number }}.wurstbot.com
  - mail.wurstbot.com
  - mail{{ node_number }}.wurstbot.com

zabbix_db_pass: supersecret

# SMTPD
smtpd_pass: supersecret

# NAGIOS
nagios_server: true
nagios_password: supersecret

# MYSQL replication related
mysql_root_pass: "supersecret"
mysql_repl_pass: "supersecret"
# mysql_is_master: false
mysql_is_slave: true
mysql_master_host: "45.32.152.181"
mysql_repl_dbs:
  - zabbix
