#python-2.7.14p1 for OpenBSD 6.3
#python-2.7.14 for OpenBSD 6.2

# BASE
install_url: https://ftp.fau.de/pub/OpenBSD
dns_name: node4.wurstbot.com
node_number: 4
node_ip: 45.32.152.181
# admin_email: s.schmidbauer@gmail.com
# admin_user: admin
admin_pass: supersecret

# SYSTEM AND PACKAGE UPDATES
update_mode: false

# PF
ext_if: vio0

# VPN
iked_tunnels:
  node4_to_node6:
    vpn_peer_ip: 209.250.244.111
    vpn_local_ip: "{{ node_ip }}"
    vpn_remote_ip: 209.250.244.111
    vpn_ikesa: auth hmac-sha1 enc aes-256 group modp1024
    vpn_childsa: enc aes-256 auth hmac-sha1 group modp1024
    vpn_srcid: "{{ node_ip }}"
    vpn_dstid: 209.250.244.111
    vpn_ikelifetime: 10800
    vpn_lifetime: 3600
    vpn_psk: supersecret
    vpn_tunnel_bandwidth: 1M

# BIRD
bgp_pass: supersecret
bgp_ha_ip: 45.76.81.117

# ACME-client
acme_aliases:
  - zabbix.wurstbot.com
  - zabbix{{ node_number }}.wurstbot.com
  - nagios.wurstbot.com
  - nagios{{ node_number }}.wurstbot.com

# ZABBIX SERVER
zabbix_db_pass: supersecret

# SMTPD
smtpd_pass: supersecret

# NAGIOS
nagios_server: true
nagios_password: supersecret

# MYSQL replication related
mysql_root_pass: "supersecret"
mysql_repl_pass: "supersecret"
mysql_is_master: true
